wallfair-organization/frontend

- src/components/FixedIconButton/styles.module.scss
- src/components/Icon/index.js
- src/components/LeaderboardItem/styles.module.scss
- src/components/Navbar/index.js
- src/components/Navbar/styles.module.scss
- src/components/Notifications/index.js
- src/components/Notifications/styles.module.scss
- src/components/NotificationsItem/styles.module.scss
- src/styles/all.scss
- src/styles/global.scss
Allows one navbar drawer open at once (closes others when one is opened), uses consistent behaviour for heading spacing related to navbar and edge-of-screen spacing.
Sets fixed width for notifications and leaderboard drawers on larger screens to avoid narrow drawers on medium screens.
> Alter navbar drawers behaviour

- src/screens/Bet/index.js
… in case previous location path is not available
> Added fallback path to home on the Event back button 

- src/components/BetView/index.js
- src/components/Button/index.js
- src/components/Button/styles.module.scss
- src/components/Events/EventsContent/index.js
Reverts wallfair-organization/frontend#208
> Revert "feat: live badge status & show Tooltip"

- src/App.tsx
- src/api/index.js
- src/components/LotteryGamePopup/index.js
- src/components/LotteryGamePopup/styles.module.scss
- src/components/Navbar/index.js
- src/components/Popup/PopupTheme.js
- src/components/Popup/index.js
- src/constants/Routes.js
- src/screens/Rewards/index.js
- src/screens/Rewards/styles.module.scss
> feat: [MVP2-138] new rewards route and page UI

- src/screens/Home/index.js
- src/screens/Home/styles.module.scss
Decentralized Events
Anytime, Anywhere
Be The House
> Changed Home Headline content

- src/components/EventTradesContainer/index.js
- src/components/EventTradesContainer/styles.module.scss
- src/helper/EventTradeViewsHelper.js
- src/screens/Bet/hooks/useTabOptions.js
- src/screens/Bet/index.js
> Hide News tab when event type is equal to 'streamed'

- src/components/PlaceBet/index.js
- src/components/RosiGameAnimation/Timer.js
- src/components/RosiGameAnimation/index.js
- src/components/RosiGameAnimation/styles.module.scss
* On the cashout field, do not change value to 0
* On the cashout field, initial value should be 1
* User must be able to change slider and cashout during animation (do not block these fields)
* Start counting from 0 not from 1
* When explosion happens, flash number in red / make number grow bigger for a second
* Fix crash factor not matching with value in last crashes bar
> Rosi game improvements

- src/components/BetView/index.js
- src/components/BetView/styles.module.scss
- src/components/RelatedBetCard/index.js
- src/components/RelatedBetCard/styles.module.scss
- src/components/TimeCounter/index.js
- src/components/TimeCounter/styles.module.scss
Hi Guilherme,
I created TImeCounter componnet to show timer like Figma design.
I updated only timer so please check it and let me know it works correct like your requirement.
)
> Create TimeCounter component to show timer like Figma design

- src/components/TokenSlider/index.js
- src/components/TokenSlider/styles.module.scss
We've have fixed the slider issue. Kindly check
> fixed slider issue

- src/components/HomeSettings/index.js
- src/components/HomeSettings/styles.module.scss
- src/components/MainMenu/index.js
- src/components/MyTradesList/index.js
- src/components/Referrals/index.js
- src/components/Referrals/styles.module.scss
- src/components/TwoColumnTable/styles.module.scss
- src/components/Wallet/index.js
- src/store/actions/general.js
- src/store/reducer/general.js
2. Move Referrals Tab to main menu
3. Revomve Wallet option in main menu
> 1. Move tabs My trades and history to wallet panel.

- src/components/PlaceBet/index.js
- src/components/PlaceBet/styles.module.scss
- src/screens/RosiGame/MobileBets.jsx
> final changes

- src/api/index.js
- src/components/EventJumbotron/index.js
- src/components/EventJumbotron/styles.module.scss
- src/components/Events/EventsContent/index.js
- src/constants/Api.js
Reverts wallfair-organization/frontend#290
> Revert "Revert "added cover stream""

- src/components/BetApproveView/index.js
- src/components/BetView/index.js
- src/components/Button/styles.module.scss
- src/components/EvaluateEventPopup/index.js
- src/components/EventJumbotron/index.js
- src/components/LotteryGamePopup/index.js
- src/components/PulloutApprovePopup/index.js
- src/components/ReportEventPopup/index.js
> Position button text above svg background in Firefox.

- src/components/BetApproveView/index.js
- src/components/Popup/styles.module.scss
- src/screens/Bet/index.js
- fix scrollbar in BetAproveView
- only 2 decimal places
- autoplay in bet view
> - add comingSoon tooltip

- src/components/PlaceBet/index.js
- src/components/PlaceBet/styles.module.scss
> Add a warning

- src/components/WalletBalance/index.js
Ticket: https://wallfair-product.atlassian.net/browse/MVP2-366
Removed Trade link from Wallet popup
> Removing trade link from the wallet

- public/index.html
@zametica Can you please check this. Added more meta tags for better readability by the crawlers
> Updating index html, adding more meta tags

- src/components/Events/EventsContent/index.js
Partially done.
Bets are listed (instead of non-streamed Events) at /events/all
_Search and sorting don't work yet._
@gmussi Please check open questions:
https://wallfair-product.atlassian.net/browse/MVP2-385?focusedCommentId=10421
> Implemented logic to show bets instead of events on Events page (partial)

- src/api/crash-game.js
- src/components/GameBets/index.js
- src/components/PlaceBet/index.js
- src/components/PlaceBet/styles.module.scss
- src/constants/Api.js
- src/screens/RosiGame/index.js
- src/store/actions/rosi-game.js
- src/store/reducer/rosi-game.js
- src/store/sagas/websockets.js
- src/store/selectors/rosi-game.js
Add reward handler
Replace cashed out selector
Add waiting status
>  Replace bets with immediate cashout in rosi game

- package-lock.json
- package.json
- src/components/EmbedVideo/Unknown.js
- src/components/EmbedVideo/VideoPlayer.js
- src/components/EmbedVideo/index.js
- src/components/EmbedVideo/styles.module.scss
- add some generic fallback, when stream is not supported
> - [MVP2-405] add support for streams m3u8

- src/components/PlaceBet/index.js
- src/store/reducer/rosi-game.js
> Add confetti

- src/components/EventsCarouselContainer/index.js
@gmussi that's a quick implementation similar to the event/all page. I'll improve it to get the bets properly from the API later.
> added bets to the non-streamed event carousel

- server/meta/index.js
Adding new meta values for static pages
> Adding new meta tags

- src/components/News/index.js
Ticket: https://wallfair-product.atlassian.net/browse/MVP2-407
Work: 
- used loadash unesacpe function
> Unseacpe htmlentities string

- src/components/BetView/index.js
Ticket: https://wallfair-product.atlassian.net/browse/MVP2-416
Work
- Changed content
> updating content of the question mark

- src/components/BetView/index.js
Reverts wallfair-organization/frontend#407
> Revert "updating content of the question mark"

- src/components/Disclaimer/index.js
Changing footer content
Made sure the links are working
> Changing footer content

- src/components/GameCards/index.js
- src/components/InfoBox/index.js
- src/components/InfoBox/styles.module.scss
- src/constants/Games.js
Ticket: https://wallfair-product.atlassian.net/browse/MVP2-417
Task: 
- Added icon on the rosi game
- Added icon styling to match the attached image
> Mvp2 417 adding icon on rosi game

- src/components/PlaceBet/index.js
- src/components/PlaceBet/styles.module.scss
Ticket: https://wallfair-product.atlassian.net/browse/MVP2-416
Work:
Added info icon in front of Place bet
> Adding place bet content

- src/components/Authentication/index.js
- src/components/Popup/index.js
Ticket: https://wallfair-product.atlassian.net/browse/MVP2-437
Work: 
- Submit SignUp and Login forms on Enter key
- Close the modal sign and login if users presses escape on keyboard
> Submit auth form using enter key and close modal on escape

- src/App.tsx
Task: https://wallfair-product.atlassian.net/browse/MVP2-442
Work: Added scroll to top for navigations, based on https://reactrouter.com/web/guides/scroll-restoration
> Mobile scroll to top

- src/App.tsx
Reverts wallfair-organization/frontend#431
> Revert "Mobile scroll to top"

- src/utils/ScrollToTop.js
> Adding component

- src/App.tsx
Reverts wallfair-organization/frontend#433
> Revert "Revert "Mobile scroll to top""

- src/components/BetView/index.js
- src/helper/Chart/chartHelpers.js
- src/helper/Chart/chartOptions.js
- move legend to bottom on mobile
- hide evidence / learn more in betting
> - remove dots from charts [desktop/mobile]

- server/meta/index.js
- src/components/ExplanationViewPopup/index.js
- src/components/PlaceBet/index.js
- src/constants/Games.js
- src/constants/Routes.js
- src/screens/Home/index.js
- src/screens/RosiGame/index.js
- src/store/sagas/websockets.js
Route changed from /rosi-game to /elon-game
All "Rosi Game" labels changes to "Elon Game"
> Changed LABELS and ROUTE from Rosi game to Elon Game

- package-lock.json
- package.json
- src/components/Share/index.js
using _react-device-detect_ module
> added condition to check if mobile device is used in order to open or not the native share function

- src/components/ActivitiesTracker/styles.module.scss
- src/screens/Bet/index.js
Task: https://wallfair-product.atlassian.net/browse/MVP2-445
Work:
- Fixed swiper issue on mobile
- Before: https://monosnap.com/file/cnDZLlrCNwZAuc4urG6GvzOhfk0Xi9
- After: https://monosnap.com/file/ibYDRi4pOqKlRpVbnZQS5CbK9HYEWt
- Issue with home page Activity section on safari desktop. fixed
> Mvp2 445 swipper issue

- src/screens/LandingPage/SectionFive/index.js
- src/screens/LandingPage/SectionFive/styles.module copy.scss
- src/screens/LandingPage/SectionFour/index.js
- src/screens/LandingPage/SectionThree/index.js
- src/screens/LandingPage/SectionTwo/index.js
> updating the content home page

- src/components/MainMenu/styles.module.scss
- src/components/NotificationCard/styles.module.scss
- src/components/Notifications/index.js
- src/components/Notifications/styles.module.scss
safari css fixes for notification component
> notifications component safari compliant

- src/components/PlaceBet/index.js
Reverts wallfair-organization/frontend#797
> Revert "deactivated auto-cashout field and logic temporarily"

- src/components/Authentication/index.js
- src/components/InputBox/index.js
Challenge, Dirk Metzler
Description:
The following tasks should be done on the Login and Signup Popup:
- input field for email: must have type=email
- input field for email: when user submits an invalid email, a little error tooltip appears. Please also validate the email when the field loses focus (user clicked somewhere else or pressed tab)
- Input field for email: Focus on this input field when the popup opens (so use can immediately start typing)
- When the user clicks Tab it should jump between the 2 or 3 input fields visible
> Improvments of Login/Signup: validation and focus

- src/components/Navbar/index.js
Updated next draft date to always next Sunday
> Updated next draft date to always next Sunday

- src/components/LeaderboardItem/index.js
Removed tooltip from leaderboard
> Removed tooltip from leaderboard

- src/api/crash-game.js
- src/components/EventActivitiesTracker/ActivityTableRow.js
- fix some typos in object property names
> - add username in lucky / High wins

- package-lock.json
- package.json
Fixed typeform popup closing issue
> Fixed typeform popup closing issue

- src/components/ContentFooter/index.js
- src/components/ExplanationViewPopup/index.js
- src/screens/Home/index.js
Removed alpha platform and gitbook
> Removed alpha platform and gitbook

- src/components/WallpaperCards/styles.module.scss
- src/screens/RosiGame/index.js
> Fix wallpapaer in a new page

- src/screens/Activities/index.js
set timer every 5s in Activities
> Update set timer every 5s in Activities

- src/api/index.js
- src/components/MainMenu/index.js
- Solved bug. Login: Error message "Session expired." displayed after invalid input.
- BUGFIX: Profile: Pictures larger than 1MB cannot be selected as your 
profile picture. A function that resize pictures bigger than 1MB.
> Some bugs fixed

- src/components/GameOffline/index.js
- src/components/GameOffline/styles.module.scss
- src/components/PumpDumpAnimation/index.js
- src/components/PumpDumpAnimation/styles.module.scss
- src/components/RosiGameAnimation/index.js
- src/components/RosiGameAnimation/styles.module.scss
- src/constants/Games.js
- src/hooks/useRosiData.js
- src/screens/RosiGame/index.js
- src/store/selectors/rosi-game.js
> Add PumpDump Animation component

- src/components/RouletteGameAnimation/AnimationController.js
Load image, added right font, fixed some problem during animation
> added images, font and change some stuff

- src/components/RouletteGameAnimation/AnimationController.js
> increased alpaca size

- src/components/PlaceBetRoulette/index.js
- src/config/gtm.js
- src/screens/RouletteGame/index.js
Added "place bet" and "place bet guest" custom tracking events to roulette game
Added data-tracking-ids to screen elements
> initial roulette tracking

- src/components/RouletteGameAnimation/AnimationController.js
- src/screens/RouletteGame/index.js
> Mobile Alpaca game, died numbers.

- src/api/casino-games.js
- src/components/PlaceBetRoulette/index.js
- src/components/PlaceBetRoulette/styles.module.scss
- src/components/RouletteGameAnimation/AnimationController.js
- src/components/RouletteGameAnimation/index.js
- src/screens/RouletteGame/index.js
> - Alpaca Game code cleaned.

- src/constants/RosiGame.js
- src/constants/RouletteGame.js
games ids coming from one file
> game ids all from one place

- src/components/GameCards/index.js
- src/components/GameCards/styles.module.scss
- src/constants/Games.js
> Updated game cards

- src/components/EventActivitiesTracker/ActivityMessage.js
- src/components/EventActivitiesTracker/ActivityTable.js
- src/components/EventActivitiesTracker/ActivityTableRow.js
- src/components/EventActivitiesTracker/index.js
- src/components/EventActivitiesTracker/styles.module.scss
- src/screens/Home/index.js
Merge alpa-prod into main to debug an issue
> Alpa Prod into main

- src/components/EventActivitiesTracker/ActivityMessage.js
- src/components/EventActivitiesTracker/ActivityTable.js
- src/components/EventActivitiesTracker/ActivityTableRow.js
- src/components/EventActivitiesTracker/index.js
- src/components/EventActivitiesTracker/styles.module.scss
- src/screens/Home/index.js
Reverts wallfair-organization/frontend#921
> Revert "Feature/mvp2 743"

- src/components/GameAudioControlsLocal/index.js
- src/components/RouletteGameAnimation/AnimationController.js
- src/components/RouletteGameAnimation/index.js
https://wallfair-product.atlassian.net/browse/MVP2-758
> fix disable default sound and kill tick sound in homepage

- src/components/EventActivitiesTracker/ActivityMessage.js
- src/components/EventActivitiesTracker/ActivityTableRow.js
- src/screens/Home/index.js
cashout number always integer.
fixed bug that was hiding big rewards
> activities numbers format

- src/components/WelcomeView/index.js
https://wallfair-product.atlassian.net/browse/MVP2-762
> fix mvp2-762 signup form fixes

- src/components/RouletteGameAnimation/styles.module.scss
fix alpha wheel volume control
> fix alpha wheel volume control

- src/api/crash-game.js
- src/components/EventActivitiesTabs/index.js
- src/components/EventActivitiesTabs/styles.module.scss
- src/screens/Home/index.js
- src/screens/PlinkoGame/index.js
- src/screens/RosiGame/index.js
- src/screens/RouletteGame/index.js
a shared component EventActivitiesTabs has all the logic and calls to show list of activities per user and game.
This component is used in home, rosigame, plinko and roulette games pages.
> activities tab is a shared component in pages

- src/components/Navbar/index.js
- src/components/Navbar/styles.module.scss
https://wallfair-product.atlassian.net/browse/MVP2-767
> mvp2-766 fix leaderboard button size

- src/components/PlaceBetRoulette/index.js
- src/components/PlaceBetRoulette/styles.module.scss
- src/components/TokenNumberInput/styles.module.scss
https://wallfair-product.atlassian.net/browse/MVP2-781
> mvp2-781 update auto bet design

- src/api/crash-game.js
the user bets api returns already the profit
> mybets negative values

- public/index.html
> favicon force cache update

- src/components/PlaceBet/index.js
- src/components/PlaceBet/styles.module.scss
- src/components/PlaceBetRoulette/index.js
- src/components/PlaceBetRoulette/styles.module.scss
- src/components/TokenNumberInput/styles.module.scss
https://wallfair-product.atlassian.net/browse/MVP2-783
> mvp2-783 update auto bet styling on elon game

- src/screens/Home/index.js
- src/screens/Home/styles.module.scss
update change game-card position
> update change game-card position

- src/components/MinesGameAnimation/game/view/index.js
> fix mobile

- src/components/Button/styles.module.scss
- src/components/GameOffline/styles.module.scss
- src/components/RosiGameAnimation/styles.module.scss
https://wallfair-product.atlassian.net/browse/MVP2-785
> mvp2-785 fix yellow elements to pink

- src/screens/Home/index.js
- src/screens/Home/styles.module.scss
update read more button for alpacaverse
> update read more button for alpacaverse

- src/screens/Home/index.js
remove activities for non-auth user
> remove activities for non-auth user

- src/screens/PlinkoGame/styles.module.scss
- src/screens/RouletteGame/styles.module.scss
fix move spins above game window
> fix move spins above game window

- src/components/ChatMessage/styles.module.scss
- src/components/PlaceBet/index.js
- src/components/PlaceBetCasino/index.js
fix change my username color to grey
> fix change my username color to grey

- src/components/PlaceBetCasino/index.js
- src/components/PlinkoGameAnimation/AnimationController.js
- src/components/PlinkoGameAnimation/index.js
- src/components/PlinkoGameAnimation/styles.module.scss
- src/screens/PlinkoGame/index.js
- Live animation for all users.
> - Fix autobet problems.

- src/components/PlaceBet/styles.module.scss
- src/components/PlaceBetCasino/index.js
- src/components/PlaceBetCasino/styles.module.scss
> update placebet area styling

- src/components/MinesGameAnimation/index.js
- src/screens/MinesGame/index.js
2. play demo, refresh game state after user login
> 1. reload game state when user will login

- src/components/PlaceBet/index.js
- src/components/PlaceBet/styles.module.scss
- src/data/backgrounds/games/bet-button.svg
> Changed label of elon game's placebet button

- src/components/PumpDumpAnimation/config.js
- src/components/PumpDumpAnimation/game/PumpDumpGameManager.js
- src/components/PumpDumpAnimation/game/game-objects/BarChartContainer.js
- src/components/PumpDumpAnimation/game/game-objects/CashOutContainer.js
- src/components/PumpDumpAnimation/game/game-objects/HorizontalAxis.js
- src/components/PumpDumpAnimation/game/game-objects/VerticalAxis.js
- src/components/PumpDumpAnimation/game/scenes/LaunchScene.js
- src/components/PumpDumpAnimation/styles.module.scss
- src/components/PumpDumpAnimation/utils/GameAudioManager.js
Launch screen changes: 1 Tweet at a time in small screen devices. 3 at max in desktop
Repositioning of the Prep round title
Bar sticks (candles) randomization
> Pump dump tweets

- src/components/AlpacaBuilder/index.js
- src/components/MainMenu/index.js
- src/store/actions/authentication.js
- src/store/reducer/authentication.js
minor changes to allow the alpaca builder to resume the state of the builder after login/logout
> mvp2-777 alpaca props updated from api

- src/components/PumpDumpAnimation/game/PumpDumpGameManager.js
- src/components/PumpDumpAnimation/game/game-objects/HorizontalAxis.js
- src/components/PumpDumpAnimation/game/game-objects/VerticalAxis.js
- src/components/PumpDumpAnimation/game/scenes/LaunchScene.js
Changing constant value of resolution from 2 to window.devicePixelRatio
> constant resolution to dpr. Round pixels removal for scales

- src/components/PlaceBet/index.js
- src/components/PlaceBetCasino/index.js
- src/components/PlaceBetMines/index.js
> Fix typo signin to sign in

- src/store/sagas/authentication.js
https://wallfair-product.atlassian.net/browse/MVP2-835
> mvp2-835 removed signup popup after 1 min not logged in

- src/components/GameBets/index.js
- src/components/LastCrashes/index.js
- src/components/PlaceBet/index.js
- src/components/PlaceBet/styles.module.scss
- src/components/PlaceBetMines/index.js
- src/components/PumpDumpAnimation/index.js
- src/components/RosiGameAnimation/Timer.js
- src/components/RosiGameAnimation/index.js
Change multiplier to percentage
> Change multiplier to percentage

- src/components/GameBets/index.js
- src/components/LastCrashes/index.js
- src/components/PlaceBet/index.js
- src/components/PlaceBet/styles.module.scss
- src/components/PlaceBetMines/index.js
- src/components/PumpDumpAnimation/index.js
- src/components/RosiGameAnimation/Timer.js
- src/components/RosiGameAnimation/index.js
Reverts wallfair-organization/frontend#1111
> Revert "Change multiplier to percentage"

- src/components/GameCards/index.js
- src/components/GameSmartsoft/index.js
- src/constants/Games.js
> Games organization

- src/store/actions/onboarding.js
- src/store/reducer/onboarding.js
- src/store/sagas/onboarding.js
temp solution for wallet onboarding step
> onboarding wallet step

- src/components/NumberCommaInput/NumberCommaInput.js
- src/components/PlaceBet/index.js
- src/components/PlaceBet/styles.module.scss
- src/components/TokenNumberInput/index.js
Reverts wallfair-organization/frontend#1286
> Revert "Improvement/place bet panels"

- src/screens/Home/index.js
force redeploy GTM tracking id from github secrets
> redeploy tracking id

- src/screens/Home/index.js
- src/screens/TermsConditions/index.js
Fix typo on numbers on T&C page
> Merge main into prod

- src/components/WalletBuyWfairPopup/Tabs/BuyWithCrypto.js
- src/components/WalletBuyWfairPopup/WalletBuyWfairPopup.js
- src/components/WalletBuyWfairPopup/styles.module.scss
- Activate Cryptopay tab
- Hide manual crypto deposit tab
> Merge main into production

- src/components/MinesGameAnimation/AnimationController.js
- src/components/MinesGameAnimation/game/controller/index.js
- src/components/MinesGameAnimation/game/index.js
- src/components/MinesGameAnimation/game/view/index.js
fade unfade symbol - add mouse over and out effects - keep revealed symbols unfaded
> fade unfade symbol - add mouse over and out effects - keep revealed

- src/components/MinesGameAnimation/AnimationController.js
- src/components/MinesGameAnimation/game/MovieClip.js
- src/components/MinesGameAnimation/game/view/index.js
- src/screens/MinesGame/index.js
> fix wrong selection

- src/components/PumpDumpAnimation/utils/Timer.js
> bug on multiplier

- src/screens/Home/index.js
- src/screens/HowItWorks/index.js
> Merge main into playm

- src/components/LeaderboardHome/index.js
- src/screens/Games/index.js
* Fixed home leaderboard currency
> Merge main into production-app

- src/components/CashoutPopupView/index.js
- src/components/WalletBuyWfairPopup/Tabs/WithdrawTab.js
* fixed crash game popup currency
* remove console.logs
> fixed crash games popup + removed console.log

- src/components/RosiGameAnimation/Timer.js
- src/screens/RosiGame/index.js
* hide crashgame win popup temporarily
* added decimals to profit counter on crash game
> Hide crashgame popup + added decimals to profit counter
